baseurl      = ""
title        = "dado1513"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Ph.D, Cyber Security enthusiast, Penetration Tester & Father"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = ["img/hello.jpg"]

  customCSS = ["css/styles.css"]
  customJS  = []
  enableThemeToggle = false


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "dado1513"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Dado1513"

    [languages.en.params.logo]
      logoText = "dado1513"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts/"

  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "https://notes.dado1513.dev"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  
  [[params.social]]
    name = "github"
    url = "https://github.com/dado1513"
  
  [[params.social]]
    name = "hackthebox"
    url = "https://app.hackthebox.com/profile/580421"
  
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/davide-caputo/"
  
  [[params.social]]
    name = "X"
    url = "https://x.com/Dado_1513"

  
    
   [params.author]
      name = "Davide Caputo"

  [params.favicon.color]
    mask = "#3ddc84"
    msapplication = "#3ddc84"
    theme = "#3ddc84"